version: '3.6'

services:
  unbscholar.lib.unb.ca:
    build:
      context: .
    restart: always
    env_file:
      - ./env/dspace.env
    container_name: unbscholar.lib.unb.ca
    ports:
      - "9987:8080"
    networks:
      - unbscholar.lib.unb.ca

  dspace-postgres-lib-unb-ca:
    build:
      context: postgres/
    restart: always
    env_file:
      - ./env/dspace.env
    networks:
      - unbscholar.lib.unb.ca

  dspace-solr-lib-unb-ca:
    build:
      context: solr/
    restart: always
    env_file:
      - ./env/dspace.env
    networks:
      - unbscholar.lib.unb.ca
    volumes:
      - ./solr/data:/data

networks:
  unbscholar.lib.unb.ca:
    name: unbscholar.lib.unb.ca
