version: '3.6'

services:

  unbscholar.lib.unb.ca:
    build:
      context: frontend/
    restart: always
    container_name: unbscholar.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "4000"
    networks:
      - unbscholar.lib.unb.ca
    ports:
      - "9988:4000"

  unbscholar.dspace.lib.unb.ca:
    build:
      context: .
    restart: always
    container_name: unbscholar.dspace.lib.unb.ca
    env_file:
      - ./env/dspace.env
    expose:
      - "8080"
    ports:
      - "9987:8080"
    networks:
      - unbscholar.lib.unb.ca

  dspace-postgres-lib-unb-ca:
    build:
      context: postgres/
    restart: always
    env_file:
      - ./env/dspace.env
    expose:
      - "5432"
    networks:
      - unbscholar.lib.unb.ca

  dspace-solr-lib-unb-ca:
    build:
      context: solr/
    restart: always
    env_file:
      - ./env/dspace.env
    expose:
      - "8983"
    networks:
      - unbscholar.lib.unb.ca
    volumes:
      - ./solr/data:/data

networks:
  unbscholar.lib.unb.ca:
    name: unbscholar.lib.unb.ca
