services:
  unbscholar.lib.unb.ca:
    build:
      args:
        BUILD_CMD: ''
        NODE_ENV: development
      context: .
    restart: unless-stopped
    container_name: unbscholar.lib.unb.ca
    env_file:
      - env/common.env
      - env/angular.env
    volumes:
       - ./build/src:/build/src
    expose:
      - "4000"
    networks:
      - unbscholar.lib.unb.ca
    ports:
      - "9988:4000"
  unbscholar.dspace.lib.unb.ca:
    build:
      context: dspace/
    restart: unless-stopped
    env_file:
      - env/common.env
      - env/dspace.env
    expose:
      - "8080"
    ports:
      - "9989:8080"
    networks:
      - unbscholar.lib.unb.ca
  unbscholar-postgres-lib-unb-ca:
    build:
      context: postgres/
    restart: unless-stopped
    env_file:
      - ./env/common.env
      - ./env/postgres.env
    expose:
      - "5432"
    networks:
      - unbscholar.lib.unb.ca
  unbscholar-solr-lib-unb-ca:
    build:
      context: solr/
    restart: unless-stopped
    env_file:
      - env/common.env
    expose:
      - "8983"
    networks:
      - unbscholar.lib.unb.ca

networks:
  unbscholar.lib.unb.ca:
    name: unbscholar.lib.unb.ca
